baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "my-theme"

[[menu.main]]
    identifier = "services"
    name = 'Services'
    url = '/services'
    weight = 1
[[menu.main]]
    identifier = "contact"
    name = 'Contact'
    url = '/contact'
    weight = 2
[[menu.main]]
    identifier = "about"
    name = 'About'
    url = '/about'
    weight = 3

[params]